import Link from "next/link";
import {
  ArrowRight, Check, ChevronDown, CircleCheck, Clock3, LockKeyhole,
  MessageSquareText, Play, Quote, ShieldCheck, Sparkles, Star, Zap,
} from "lucide-react";

const faqs = [
  ["Does Reply Pilot connect with Google Business Profile?", "Yes. Connect your Google Business Profile in a few guided steps and Reply Pilot begins monitoring your selected location."],
  ["Will the replies sound like my business?", "They are created from your brand voice, preferred tone, and response length, so the experience stays consistent for your customers."],
  ["Can I control or disable automation?", "Absolutely. You can change your automation settings or turn automated replies off whenever you need to."],
  ["Can I manage multiple locations?", "Reply Pilot currently supports one selected location per workspace. Multi-location management is on the product roadmap."],
  ["Is my Google account secure?", "Google access is handled through OAuth and credentials are encrypted. Reply Pilot only uses the access needed to manage review replies."],
];

function Logo({ dark = false }: { dark?: boolean }) {
  return <span className={`inline-flex items-center gap-2 font-semibold tracking-[-0.04em] ${dark ? "text-white" : "text-slate-950"}`}><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#2857f5] text-sm font-black text-white">R</span>Reply Pilot</span>;
}

export default function Home() {
  return <main className="overflow-hidden bg-[#fbfbfa] text-slate-950">
    <nav className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-8">
      <Logo />
      <div className="hidden items-center gap-8 text-sm font-medium text-slate-600 md:flex"><a href="#product">Product</a><a href="#how-it-works">How it works</a><a href="#pricing">Pricing</a></div>
      <div className="flex items-center gap-3 text-sm font-semibold"><Link className="hidden px-3 py-2 text-slate-700 sm:block" href="/login">Log in</Link><Link className="rounded-full bg-slate-950 px-4 py-2.5 text-white shadow-lg shadow-slate-900/15 transition hover:-translate-y-0.5 hover:bg-[#2857f5]" href="/register">Start Free <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></Link></div>
    </nav>

    <section className="relative mx-auto max-w-7xl px-6 pb-12 pt-14 text-center lg:px-8 lg:pb-16 lg:pt-24">
      <div className="hero-glow" />
      <div className="relative mx-auto max-w-4xl"><p className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white px-4 py-2 text-xs font-semibold text-[#2857f5] shadow-sm"><Sparkles className="h-3.5 w-3.5" /> The always-on customer care teammate</p>
        <h1 className="mt-7 text-5xl font-semibold leading-[1.01] tracking-[-0.07em] text-slate-950 sm:text-6xl lg:text-7xl">Every review answered.<br />Like you never missed it.</h1>
        <p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-slate-600">Reply Pilot detects new Google reviews, writes a thoughtful response in your voice, and publishes it—automatically.</p>
        <div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/register" className="rounded-full bg-[#2857f5] px-6 py-3.5 text-sm font-semibold text-white shadow-xl shadow-blue-600/25 transition hover:-translate-y-0.5 hover:bg-blue-700">Start Free <ArrowRight className="ml-1 inline h-4 w-4" /></Link><a href="#product" className="rounded-full px-6 py-3.5 text-sm font-semibold text-slate-700 transition hover:text-[#2857f5]"><Play className="mr-1 inline h-4 w-4 fill-current" /> See it in action</a></div>
        <p className="mt-6 text-xs font-medium text-slate-500"><ShieldCheck className="mr-1 inline h-3.5 w-3.5 text-[#2857f5]" /> Secure Google Business Profile connection</p>
      </div>
      <ProductDemo />
    </section>

    <section className="border-y border-slate-200 bg-white py-8"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-5 px-6 text-center sm:flex-row sm:text-left"><p className="text-sm font-medium text-slate-500">Built for the conversations happening on</p><div className="flex items-center gap-3 text-lg font-semibold tracking-[-.04em] text-slate-700"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#4285f4] text-xs text-white">G</span>Google Business Profile</div><p className="text-xs font-medium text-slate-400">Connect securely with OAuth</p></div></section>

    <section id="product" className="py-24 sm:py-32"><div className="mx-auto max-w-6xl px-6"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">A REVIEW-TO-REPLY SYSTEM</p><h2>One calm workflow for every new review.</h2><p className="copy mx-auto">The work happens in the background. You get a response history you can trust, without adding another task to your team.</p></div><div className="mt-16 grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div className="space-y-0"><StoryStep n="01" title="A review arrives" body="Reply Pilot keeps an eye on your selected Google Business Profile." active /><StoryStep n="02" title="AI understands the moment" body="Rating and message become context for an appropriate response." /><StoryStep n="03" title="Your voice shapes the reply" body="Tone and preferred length stay consistent across every answer." /><StoryStep n="04" title="A response goes live" body="A polished reply is published while the moment still matters." /></div><ReviewWindow /></div></div></section>

    <section className="relative bg-[#f1f5ff] py-24 sm:py-32"><div className="section-aura" /><div className="relative mx-auto grid max-w-6xl gap-16 px-6 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">THE COST OF SILENCE</p><h2>Great experiences deserve a response.</h2><p className="copy">Responding manually is repetitive, inconsistent, and easy to let slide. Each review is a chance to show customers they were heard—without asking your team to watch another inbox.</p><Link href="/register" className="text-link">Let Reply Pilot handle it <ArrowRight /></Link></div><div className="border-l border-blue-200 pl-7 sm:pl-10"><p className="text-sm font-semibold text-slate-950">The old way has too many handoffs</p>{["Notice a new review", "Find time to write a reply", "Try to match your usual tone", "Remember to publish it"].map((item, i) => <div className="relative mt-7 flex items-center gap-4" key={item}><span className="relative z-10 grid h-8 w-8 place-items-center rounded-full bg-white text-xs font-bold text-[#2857f5] shadow-sm">{i + 1}</span><p className="text-base text-slate-600">{item}</p></div>)}</div></div></section>

    <section id="how-it-works" className="bg-slate-950 py-24 text-white sm:py-32"><div className="mx-auto max-w-6xl px-6"><div className="max-w-2xl"><p className="eyebrow text-blue-300">HOW IT WORKS</p><h2 className="text-white">Set the direction once.<br />Stay present, automatically.</h2></div><div className="relative mt-16 grid gap-10 md:grid-cols-4 md:gap-6"><div className="timeline-line" />{[["01", "Connect", "Securely connect your Google Business Profile."], ["02", "Choose your voice", "Set the tone and response length your business needs."], ["03", "Turn on automation", "Reply Pilot watches for each new review."], ["04", "Keep the relationship moving", "Thoughtful replies publish while they still matter."]].map(([n, title, body]) => <article className="relative" key={n}><span className="grid h-11 w-11 place-items-center rounded-full border border-blue-300/30 bg-slate-950 text-sm font-semibold text-blue-200">{n}</span><h3 className="mt-6 text-lg text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{body}</p></article>)}</div></div></section>

    <section className="py-24 sm:py-32"><div className="mx-auto max-w-6xl px-6"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">FULL VISIBILITY, ZERO CHASING</p><h2>Your customer care,<br />at a glance.</h2></div><p className="max-w-sm text-base leading-7 text-slate-600">A clear view of what has arrived, what was written, and what is now live.</p></div><Dashboard /></div></section>

    <section className="border-y border-slate-200 bg-white py-24"><div className="mx-auto max-w-6xl px-6"><div className="grid gap-14 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">MADE FOR STEADY, CONSISTENT CARE</p><h2>Less switching. More showing up.</h2><p className="copy">Reply Pilot brings the repetitive pieces of review management into one dependable flow.</p></div><div className="grid gap-y-10 sm:grid-cols-2 sm:gap-x-12"><EditorialFeature icon={<Zap />} title="Always watching" text="New reviews do not wait for the next time someone checks." /><EditorialFeature icon={<MessageSquareText />} title="Voice-aware replies" text="Your settings keep each message aligned with your brand." /><EditorialFeature icon={<Clock3 />} title="Visible history" text="Know exactly what was answered and when it was published." /><EditorialFeature icon={<ShieldCheck />} title="Control when needed" text="Update automation settings whenever your business changes." /></div></div></div></section>

    <section className="bg-[#f1f5ff] py-24 sm:py-32"><div className="mx-auto max-w-6xl px-6"><div className="text-center"><p className="eyebrow">THE BETTER WAY TO REPLY</p><h2>Care should not depend on<br />who has time today.</h2></div><div className="mx-auto mt-14 max-w-4xl"><div className="grid grid-cols-3 border-b border-slate-300 pb-4 text-xs font-semibold uppercase tracking-[.1em]"><span>What changes</span><span className="text-slate-400">Manual replies</span><span className="text-[#2857f5]">Reply Pilot</span></div>{[["Time each week", "Hours of staff time", "Set it and forget it"], ["Response speed", "Whenever you get to it", "Typically minutes"], ["Brand consistency", "Depends on who replies", "Voice-guided every time"], ["Scale", "More reviews, more work", "A repeatable workflow"]].map((row) => <div className="grid grid-cols-3 border-b border-slate-200 py-5 text-sm last:border-0" key={row[0]}><span className="font-medium">{row[0]}</span><span className="text-slate-500">{row[1]}</span><span className="font-medium text-[#2857f5]"><Check className="mr-1 inline h-4 w-4" />{row[2]}</span></div>)}</div></div></section>

    <section className="py-24 sm:py-32"><div className="mx-auto max-w-5xl px-6"><div className="border-b border-slate-200 pb-12 text-center"><p className="eyebrow">BUILT FOR BUSY TEAMS</p><h2>Every response can still feel personal.</h2></div><figure className="mx-auto max-w-3xl py-16 text-center"><Quote className="mx-auto h-8 w-8 text-[#2857f5]" /><blockquote className="mt-7 text-2xl font-medium leading-[1.35] tracking-[-.035em] text-slate-800 sm:text-3xl">“It’s like adding a dedicated customer-care teammate without adding another task to our team.”</blockquote><figcaption className="mt-8 flex items-center justify-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-blue-100 text-xs font-semibold text-[#2857f5]">AB</span><span className="text-left"><b className="block text-sm">Amara Brooks</b><small className="text-slate-500">Operations, Hearth &amp; Co.</small></span></figcaption></figure><div className="grid gap-8 border-t border-slate-200 pt-10 sm:grid-cols-2"><SmallQuote quote="We used to catch up on reviews every Friday. Now they’re handled before our morning coffee." name="Maya Chen" role="Owner, Northstar Dental" /><SmallQuote quote="The replies feel natural and match the welcoming tone we’ve worked hard to build." name="Liam Foster" role="Founder, Verde Studio" /></div></div></section>

    <section id="pricing" className="bg-slate-950 py-24 sm:py-32"><div className="mx-auto max-w-6xl px-6 text-center"><p className="eyebrow text-blue-300">SIMPLE, TRANSPARENT PRICING</p><h2 className="text-white">Make every review count.</h2><p className="copy mx-auto text-slate-400">Start free. Upgrade only when your review volume grows.</p><div className="mt-14 grid gap-4 text-left lg:grid-cols-3">{[["Starter", "$29", "For one location getting started", ["1 Google Business Profile", "Automatic review detection", "Brand voice settings"]], ["Growth", "$79", "For growing teams that want full automation", ["Everything in Starter", "Automatic publishing", "Priority support", "Advanced automation controls"]], ["Agency", "Let’s talk", "For teams planning multiple locations", ["Everything in Growth", "Multi-location roadmap access", "Dedicated onboarding"]]].map(([name, price, desc, list], i) => <article className={`relative rounded-2xl border p-7 ${i === 1 ? "border-blue-400 bg-white text-slate-950 shadow-xl shadow-blue-500/20" : "border-white/10 bg-white/5 text-white"}`} key={String(name)}>{i === 1 && <span className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-[#2857f5] px-3 py-1 text-xs font-semibold text-white">MOST POPULAR</span>}<h3>{name}</h3><p className={`mt-2 min-h-10 text-sm ${i === 1 ? "text-slate-600" : "text-slate-400"}`}>{desc}</p><p className="mt-6 text-4xl font-semibold tracking-[-.05em]">{price}<span className={`text-base font-medium ${i === 1 ? "text-slate-400" : "text-slate-500"}`}>{i < 2 && "/mo"}</span></p><Link href="/register" className={`mt-7 block rounded-full py-3 text-center text-sm font-semibold ${i === 1 ? "bg-[#2857f5] text-white" : "bg-white text-slate-950"}`}>{i === 2 ? "Contact us" : "Start Free"}</Link><ul className={`mt-7 space-y-3 border-t pt-6 text-sm ${i === 1 ? "border-slate-200 text-slate-600" : "border-white/10 text-slate-300"}`}>{(list as string[]).map(x => <li key={x}><Check className="mr-2 inline h-4 w-4 text-blue-400" />{x}</li>)}</ul></article>)}</div></div></section>

    <section id="faq" className="py-24"><div className="mx-auto grid max-w-6xl gap-12 px-6 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">QUESTIONS, ANSWERED</p><h2>Everything you need to know.</h2><p className="copy">Still curious? We’re happy to help.</p><a className="text-link" href="mailto:hello@replypilot.com">Talk to us <ArrowRight /></a></div><div>{faqs.map(([question, answer], i) => <details open={i === 0} className="group border-b border-slate-200 py-5" key={question}><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold">{question}<ChevronDown className="h-5 w-5 shrink-0 text-slate-400 transition group-open:rotate-180" /></summary><p className="max-w-xl pt-3 text-sm leading-6 text-slate-600">{answer}</p></details>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-6 pb-20"><div className="relative overflow-hidden rounded-3xl bg-[#2857f5] px-6 py-16 text-center text-white sm:px-12 sm:py-24"><div className="cta-orb cta-orb-a" /><div className="cta-orb cta-orb-b" /><div className="relative"><p className="text-sm font-semibold text-blue-200">YOUR NEXT REVIEW IS WAITING</p><h2 className="mx-auto mt-4 max-w-3xl text-white">Never leave another customer review unanswered.</h2><p className="mx-auto mt-5 max-w-xl text-blue-100">Connect once, then let Reply Pilot keep the conversation moving in your voice.</p><Link href="/register" className="mt-8 inline-block rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-[#2857f5] shadow-lg transition hover:-translate-y-0.5">Start Free <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div></div></section>

    <footer className="border-t border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-12 sm:grid-cols-2 lg:grid-cols-5"><div className="lg:col-span-2"><Logo /><p className="mt-4 max-w-xs text-sm leading-6 text-slate-500">The always-on teammate for thoughtful Google review replies.</p></div>{[["Product", "Features", "Pricing", "Changelog"], ["Company", "Documentation", "Contact", "Privacy", "Terms"], ["Follow", "LinkedIn", "X / Twitter"]].map(([head, ...links]) => <div key={head}><p className="text-sm font-semibold">{head}</p>{links.map(x => <a className="mt-3 block text-sm text-slate-500 hover:text-[#2857f5]" href="#" key={x}>{x}</a>)}</div>)}</div><div className="mx-auto flex max-w-7xl flex-col gap-2 border-t border-slate-100 px-6 py-6 text-xs text-slate-400 sm:flex-row sm:justify-between"><span>© 2026 Reply Pilot. All rights reserved.</span><span className="inline-flex items-center gap-1"><LockKeyhole className="h-3 w-3" /> Secure Google Business Profile connection</span></div></footer>
  </main>;
}

function ProductDemo() { return <div className="relative mx-auto mt-16 max-w-6xl text-left"><div className="demo-halo" /><div className="relative overflow-hidden rounded-2xl border border-slate-200 bg-white p-3 shadow-[0_35px_90px_-38px_rgba(30,50,100,.45)]"><div className="rounded-xl bg-[#f5f7fb] p-5 sm:p-7"><div className="flex items-center justify-between border-b border-slate-200 pb-5"><div><p className="text-[10px] font-bold tracking-[.14em] text-slate-400">LIVE AUTOMATION</p><p className="mt-1 text-base font-semibold">A new review is moving through your workflow</p></div><span className="flex items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700"><i className="live-dot h-1.5 w-1.5 rounded-full bg-emerald-500" /> Live</span></div><div className="relative mt-7 grid gap-3 sm:grid-cols-4"><div className="flow-line" />{[["01", "Review arrives", "Sarah M. · 5 stars", Star], ["02", "AI detects", "Just now", Sparkles], ["03", "AI writes", "Your brand voice", MessageSquareText], ["04", "Published", "Reply is live", CircleCheck]].map(([n, title, body, Icon], i) => <div className="relative bg-[#f5f7fb]" key={title as string}><span className={`grid h-9 w-9 place-items-center rounded-xl ${i === 3 ? "bg-[#2857f5] text-white" : "bg-white text-[#2857f5] shadow-sm"}`}><Icon className="h-4 w-4" /></span><p className="mt-4 text-sm font-semibold">{title as string}</p><p className="mt-1 text-xs text-slate-500">{body as string}</p></div>)}</div><div className="mt-8 grid gap-4 rounded-xl bg-white p-4 shadow-sm sm:grid-cols-[auto_1fr_auto]"><div className="grid h-10 w-10 place-items-center rounded-full bg-amber-100 text-sm font-bold text-amber-700">S</div><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">Sarah Mitchell</p><span className="flex text-amber-400"><Star className="h-3.5 w-3.5 fill-current" /><Star className="h-3.5 w-3.5 fill-current" /><Star className="h-3.5 w-3.5 fill-current" /><Star className="h-3.5 w-3.5 fill-current" /><Star className="h-3.5 w-3.5 fill-current" /></span></div><p className="mt-1 text-sm text-slate-600">Wonderful experience. The team made everything so easy!</p><div className="mt-3 border-l-2 border-[#2857f5] bg-blue-50/70 px-3 py-2.5 text-sm leading-6 text-slate-600"><span className="font-semibold text-[#2857f5]">Reply Pilot </span>Thank you, Sarah! We’re so glad our team could make your visit easy. We truly appreciate you taking the time to share this.</div></div><span className="self-start text-xs font-medium text-emerald-600">Published</span></div></div></div></div> }
function StoryStep({ n, title, body, active = false }: { n: string; title: string; body: string; active?: boolean }) { return <div className={`border-l-2 py-4 pl-5 ${active ? "border-[#2857f5]" : "border-slate-200"}`}><span className="text-xs font-bold tracking-[.12em] text-[#2857f5]">{n}</span><h3 className="mt-1 text-lg">{title}</h3><p className="mt-1 max-w-sm text-sm leading-6 text-slate-600">{body}</p></div>; }
function ReviewWindow() { return <div className="overflow-hidden rounded-2xl bg-slate-950 p-3 shadow-2xl shadow-slate-900/15"><div className="rounded-xl bg-[#121a2d] p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold tracking-[.14em] text-slate-500">REPLY PILOT</p><p className="mt-1 text-base font-semibold text-white">Review activity</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1.5 text-xs font-semibold text-emerald-300">Automation on</span></div><div className="mt-7 space-y-3"><Activity name="Taylor Reed" stars="5" text="The staff were helpful from the first call." status="Reply published" /><Activity name="Morgan Park" stars="4" text="Easy booking and a warm welcome." status="Writing response" writing /><Activity name="Jamie Cole" stars="5" text="Exactly what we needed. Thank you!" status="Queued" /></div></div></div>; }
function Activity({ name, stars, text, status, writing }: { name: string; stars: string; text: string; status: string; writing?: boolean }) { return <div className="flex gap-3 border-b border-white/10 pb-4 last:border-0 last:pb-0"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-blue-400/15 text-xs font-semibold text-blue-200">{name.split(" ").map(x => x[0]).join("")}</span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium text-white">{name} <span className="ml-1 text-amber-300">{"★".repeat(Number(stars))}</span></p><span className={`text-[11px] ${writing ? "text-blue-300" : "text-slate-400"}`}>{writing && <i className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-blue-400" />}{status}</span></div><p className="mt-1 truncate text-xs text-slate-400">{text}</p></div></div>; }
function Dashboard() { return <div className="mt-14 overflow-hidden rounded-2xl border border-slate-200 bg-white p-3 shadow-[0_28px_75px_-35px_rgba(30,50,100,.35)]"><div className="grid min-h-[400px] grid-cols-[180px_1fr] overflow-hidden rounded-xl bg-[#f6f8fc]"><aside className="hidden border-r border-slate-200 bg-white p-5 sm:block"><Logo /><p className="mt-9 text-xs font-semibold text-slate-400">WORKSPACE</p>{["Overview", "Reviews", "Automation", "Brand voice"].map((item, i) => <div className={`mt-2 rounded-lg px-3 py-2 text-sm ${i === 0 ? "bg-blue-50 font-medium text-[#2857f5]" : "text-slate-500"}`} key={item}>{item}</div>)}</aside><div className="p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-medium text-slate-400">GOOD MORNING, ALEX</p><h3 className="mt-1 text-xl">Your automation is on track</h3></div><span className="hidden rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-700 sm:block">● Automation on</span></div><div className="mt-7 grid gap-6 border-y border-slate-200 py-5 sm:grid-cols-3"><Metric title="New reviews" value="3" /><Metric title="Responses ready" value="2" /><Metric title="Published today" value="8" /></div><div className="mt-6"><div className="mb-3 flex justify-between"><p className="text-sm font-semibold">Recent reply activity</p><span className="text-xs font-medium text-[#2857f5]">View all</span></div>{["Taylor R. — 5 stars", "Morgan P. — 4 stars", "Jamie L. — 5 stars"].map((item, i) => <div className="flex items-center justify-between border-t border-slate-200 py-3 text-sm" key={item}><span>{item}</span><span className="text-xs text-emerald-600">Published · {i + 1}m ago</span></div>)}</div></div></div></div>; }
function Metric({ title, value }: { title: string; value: string }) { return <div><p className="text-2xl font-semibold tracking-[-.05em]">{value}</p><p className="mt-1 text-xs text-slate-500">{title}</p></div>; }
function EditorialFeature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div><span className="text-[#2857f5] [&>svg]:h-5 [&>svg]:w-5">{icon}</span><h3 className="mt-4 text-lg">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>; }
function SmallQuote({ quote, name, role }: { quote: string; name: string; role: string }) { return <figure><blockquote className="text-base leading-7 text-slate-600">“{quote}”</blockquote><figcaption className="mt-5 text-sm"><b>{name}</b><span className="ml-2 text-slate-500">{role}</span></figcaption></figure>; }
