import Link from "next/link";
import {
  ArrowRight, Bot, Check, ChevronDown, Clock3, Gauge, Globe2, Heart,
  LockKeyhole, MessageSquareText, Play, Quote, ShieldCheck, Sparkles, Star,
  Zap,
} from "lucide-react";

const features = [
  ["Instant detection", "Reply Pilot keeps watch for each new Google review, day and night.", Zap],
  ["Replies that sound like you", "Set your voice once. Every reply stays warm, specific, and on-brand.", MessageSquareText],
  ["Automatic publishing", "From review to published response, the workflow runs without a handoff.", Bot],
  ["Sentiment-aware care", "Thoughtful acknowledgement for praise, questions, and tougher feedback.", Heart],
  ["Clear response history", "See every automated reply and keep a complete customer-care record.", Clock3],
  ["Automation controls", "Choose the response length, voice, and exactly when automation runs.", Gauge],
];

const faqs = [
  ["Does Reply Pilot connect with Google Business Profile?", "Yes. Connect your Google Business Profile in a few guided steps and Reply Pilot begins monitoring your selected location."],
  ["Will the replies sound like my business?", "They are created from your brand voice, preferred tone, and response length, so the experience stays consistent for your customers."],
  ["Can I control or disable automation?", "Absolutely. You can change your automation settings or turn automated replies off whenever you need to."],
  ["Can I manage multiple locations?", "Reply Pilot currently supports one selected location per workspace. Multi-location management is on the product roadmap."],
  ["Is my Google account secure?", "Google access is handled through OAuth and credentials are encrypted. Reply Pilot only uses the access needed to manage review replies."],
  ["How long does setup take?", "Most businesses can connect their profile and choose their voice in just a few minutes."],
];

function Logo({ dark = false }: { dark?: boolean }) {
  return <span className={`inline-flex items-center gap-2 font-semibold tracking-[-0.04em] ${dark ? "text-white" : "text-slate-950"}`}><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#2857f5] text-white"><span className="text-sm font-black">R</span></span>Reply Pilot</span>;
}

export default function Home() {
  return <main className="overflow-hidden bg-[#fbfbfa] text-slate-950">
    <nav className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-8">
      <Logo />
      <div className="hidden items-center gap-8 text-sm font-medium text-slate-600 md:flex"><a href="#features">Features</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></div>
      <div className="flex items-center gap-3 text-sm font-semibold"><Link className="hidden px-3 py-2 text-slate-700 sm:block" href="/login">Log in</Link><Link className="rounded-full bg-slate-950 px-4 py-2.5 text-white shadow-lg shadow-slate-900/15 transition hover:-translate-y-0.5 hover:bg-[#2857f5]" href="/register">Start Free <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></Link></div>
    </nav>

    <section className="relative mx-auto max-w-7xl px-6 pb-20 pt-16 text-center lg:px-8 lg:pb-28 lg:pt-24">
      <div className="hero-glow" />
      <div className="relative mx-auto max-w-4xl"><p className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white px-4 py-2 text-xs font-semibold text-[#2857f5] shadow-sm"><Sparkles className="h-3.5 w-3.5" /> Your always-on customer care teammate</p>
        <h1 className="mt-7 text-5xl font-semibold leading-[1.02] tracking-[-0.065em] text-slate-950 sm:text-6xl lg:text-7xl">Your AI Employee for<br className="hidden sm:block" /> Google Review Replies.</h1>
        <p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-slate-600">Reply Pilot automatically detects new Google reviews and publishes personalized, human-like replies 24/7, so you never miss a customer while saving hours every week.</p>
        <div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/register" className="rounded-full bg-[#2857f5] px-6 py-3.5 text-sm font-semibold text-white shadow-xl shadow-blue-600/25 transition hover:-translate-y-0.5 hover:bg-blue-700">Start Free <ArrowRight className="ml-1 inline h-4 w-4" /></Link><a href="#how-it-works" className="rounded-full border border-slate-200 bg-white px-6 py-3.5 text-sm font-semibold text-slate-800 transition hover:border-slate-400"><Play className="mr-1 inline h-4 w-4 fill-current" /> Watch demo</a></div>
        <div className="mt-7 flex flex-wrap justify-center gap-x-5 gap-y-2 text-xs font-medium text-slate-500"><span><Check className="mr-1 inline h-3.5 w-3.5 text-[#2857f5]" />24/7 Automated</span><span><Check className="mr-1 inline h-3.5 w-3.5 text-[#2857f5]" />Setup in Minutes</span><span><ShieldCheck className="mr-1 inline h-3.5 w-3.5 text-[#2857f5]" />Secure</span></div>
      </div>
      <div className="relative mx-auto mt-16 max-w-5xl rounded-2xl border border-slate-200 bg-white p-3 text-left shadow-[0_28px_75px_-35px_rgba(30,50,100,.35)]">
        <div className="rounded-xl bg-[#f5f7fb] p-4 sm:p-7"><div className="mb-7 flex items-center justify-between"><div><p className="text-xs font-medium text-slate-400">AUTOMATION ACTIVITY</p><p className="mt-1 text-base font-semibold">Your review engine is working</p></div><span className="flex items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700"><i className="h-1.5 w-1.5 rounded-full bg-emerald-500" /> Live</span></div>
          <div className="grid gap-3 text-left sm:grid-cols-4"><FlowCard n="01" title="New Google Review" text="Sarah M. · 5 stars" icon="★" /><FlowCard n="02" title="AI Detects Review" text="Just now" icon="◌" /><FlowCard n="03" title="AI Generates Reply" text="In your brand voice" icon="✦" /><FlowCard n="04" title="Automatically Published" text="Reply posted" icon="✓" active /></div>
          <div className="mt-5 rounded-xl border border-blue-100 bg-white p-4 shadow-sm"><div className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-amber-100 text-sm font-bold text-amber-700">S</div><div className="min-w-0 flex-1"><div className="flex justify-between"><p className="text-sm font-semibold">Sarah Mitchell <span className="ml-1 text-amber-400">★★★★★</span></p><p className="text-xs text-slate-400">2 min ago</p></div><p className="mt-1 text-sm text-slate-600">Wonderful experience. The team made everything so easy!</p><div className="mt-3 rounded-lg bg-blue-50 p-3 text-sm text-slate-600"><span className="font-semibold text-[#2857f5]">Reply Pilot </span>Thank you, Sarah! We&apos;re so glad our team could make your visit easy. We truly appreciate you taking the time to share this.</div></div></div></div>
        </div>
      </div>
    </section>

    <section className="border-y border-slate-200 bg-white py-10"><div className="mx-auto max-w-6xl px-6 text-center"><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-400">Trusted by businesses that care about every customer</p><div className="mt-7 flex flex-wrap items-center justify-center gap-x-12 gap-y-5 text-xl font-semibold tracking-[-.04em] text-slate-400"><span>northstar</span><span>VERDE</span><span>Hearth &amp; Co.</span><span>STUDIO NINE</span><span>morrow</span></div></div></section>

    <section className="mx-auto grid max-w-6xl grid-cols-2 divide-x divide-y divide-slate-200 px-6 py-16 text-center md:grid-cols-4 md:divide-y-0"><Stat value="4.9/5" label="average rating"/><Stat value="12,000+" label="businesses served"/><Stat value="1.8M" label="reviews replied to"/><Stat value="< 2 min" label="average response time"/></section>

    <section className="bg-[#f1f5ff] py-24 sm:py-32"><div className="mx-auto grid max-w-6xl gap-14 px-6 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">THE COST OF SILENCE</p><h2>Great customer experiences deserve a response.</h2><p className="copy">Reviews arrive every day, but responding manually is repetitive, inconsistent, and easy to let slide. Every unanswered customer is a missed chance to build trust.</p><Link href="/register" className="text-link">Let Reply Pilot handle it <ArrowRight /></Link></div><div className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="mb-5 text-sm font-semibold">The manual review loop</p>{["Notice a new review", "Find time to write a reply", "Try to match your usual tone", "Remember to publish it"].map((x, i) => <div className="flex items-center gap-4 rounded-xl bg-slate-50 p-4" key={x}><span className="grid h-7 w-7 place-items-center rounded-full bg-slate-200 text-xs font-bold text-slate-500">{i + 1}</span><span className="flex-1 text-sm text-slate-600">{x}</span><span className="text-xs font-medium text-rose-500">often missed</span></div>)}</div></div></section>

    <section id="features" className="py-24 sm:py-32"><div className="mx-auto max-w-6xl px-6 text-center"><p className="eyebrow">MEET YOUR NEW TEAMMATE</p><h2>It does the replying.<br />You keep doing what you do best.</h2><p className="copy mx-auto">Reply Pilot is the AI employee that monitors, writes, and publishes thoughtful Google review replies—automatically, in your voice.</p><div className="mt-14 grid gap-4 text-left sm:grid-cols-2 lg:grid-cols-3">{features.map(([title, text, Icon]) => <article className="group rounded-2xl border border-slate-200 bg-white p-6 transition duration-300 hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl hover:shadow-blue-900/5" key={title as string}><span className="mb-5 grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-[#2857f5]"><Icon className="h-5 w-5" /></span><h3>{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text as string}</p></article>)}</div></div></section>

    <section id="how-it-works" className="bg-slate-950 py-24 text-white sm:py-32"><div className="mx-auto max-w-6xl px-6"><div className="max-w-xl"><p className="eyebrow text-blue-300">HOW IT WORKS</p><h2 className="text-white">Set it up once.<br />Every reply gets handled.</h2><p className="copy text-slate-400">From your first connection onward, Reply Pilot turns a new review into a published reply while you focus on your customers.</p></div><div className="mt-14 grid gap-4 md:grid-cols-4">{[["01", "Connect", "Securely connect your Google Business Profile."], ["02", "Monitor", "We spot every new review as it arrives."], ["03", "Personalize", "Your voice guides a relevant reply."], ["04", "Publish", "A polished response goes live automatically."]].map(([n, title, body]) => <div className="relative rounded-2xl border border-white/10 bg-white/5 p-6" key={n}><span className="text-sm font-semibold text-blue-300">{n}</span><h3 className="mt-12 text-lg text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{body}</p></div>)}</div></div></section>

    <section className="py-24 sm:py-32"><div className="mx-auto max-w-6xl px-6"><div className="text-center"><p className="eyebrow">FULL VISIBILITY, ZERO CHASING</p><h2>Your customer care, at a glance.</h2></div><div className="mt-14 overflow-hidden rounded-2xl border border-slate-200 bg-white p-3 shadow-[0_28px_75px_-35px_rgba(30,50,100,.35)]"><div className="grid min-h-[390px] grid-cols-[180px_1fr] overflow-hidden rounded-xl bg-[#f6f8fc]"><aside className="hidden border-r border-slate-200 bg-white p-5 sm:block"><Logo /><p className="mt-9 text-xs font-semibold text-slate-400">WORKSPACE</p>{["Overview", "Reviews", "Automation", "Brand voice", "Analytics"].map((x, i) => <div className={`mt-2 rounded-lg px-3 py-2 text-sm ${i === 0 ? "bg-blue-50 font-medium text-[#2857f5]" : "text-slate-500"}`} key={x}>{x}</div>)}</aside><div className="p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-medium text-slate-400">GOOD MORNING, ALEX</p><h3 className="mt-1 text-xl">Your automation is on track</h3></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-700">● Automation on</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><DashStat n="24" t="Replies this week"/><DashStat n="1m 42s" t="Avg. response time"/><DashStat n="100%" t="Automation rate"/></div><div className="mt-5 rounded-xl border border-slate-200 bg-white p-4"><div className="mb-4 flex justify-between"><p className="text-sm font-semibold">Recent reply activity</p><span className="text-xs font-medium text-[#2857f5]">View all</span></div>{["Taylor R. — 5 stars", "Morgan P. — 4 stars", "Jamie L. — 5 stars"].map((x, i) => <div className="flex items-center justify-between border-t border-slate-100 py-3 text-sm" key={x}><span>{x}</span><span className="text-xs text-emerald-600">Published · {i + 1}m ago</span></div>)}</div></div></div></div></div></section>

    <section className="bg-[#f1f5ff] py-24"><div className="mx-auto max-w-6xl px-6"><div className="text-center"><p className="eyebrow">THE BETTER WAY TO REPLY</p><h2>Manual effort in. Consistent care out.</h2></div><div className="mx-auto mt-12 max-w-4xl overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="grid grid-cols-3 border-b border-slate-200 p-5 text-sm font-semibold"><span>What changes</span><span className="text-slate-400">Manual replies</span><span className="text-[#2857f5]">Reply Pilot</span></div>{[["Time each week", "Hours of staff time", "Set it and forget it"], ["Response speed", "Whenever you get to it", "Typically minutes"], ["Brand consistency", "Depends on who replies", "Voice-guided every time"], ["Scale", "More locations, more work", "Multi-location workflows coming soon"]].map((r) => <div className="grid grid-cols-3 border-b border-slate-100 p-5 text-sm last:border-0" key={r[0]}><span className="font-medium">{r[0]}</span><span className="text-slate-500">{r[1]}</span><span className="font-medium text-[#2857f5]"><Check className="mr-1 inline h-4 w-4" />{r[2]}</span></div>)}</div></div></section>

    <section className="py-24"><div className="mx-auto max-w-6xl px-6"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">THE RESULTS ADD UP</p><h2>More responses. Less on your plate.</h2></div><p className="max-w-md text-slate-600">Placeholder results based on typical automated review-reply workflows.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Result n="1m 42s" l="average response time"/><Result n="14 hrs" l="saved per month"/><Result n="98%" l="reviews replied to"/><Result n="4.9/5" l="customer satisfaction"/></div></div></section>

    <section className="bg-slate-950 py-24"><div className="mx-auto max-w-6xl px-6"><div className="text-center"><p className="eyebrow text-blue-300">LOVED BY BUSY TEAMS</p><h2 className="text-white">They stopped chasing reviews.</h2></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{[["We used to catch up on reviews every Friday. Now they&apos;re handled before our morning coffee.", "Maya Chen", "Owner, Northstar Dental", "MC"], ["The replies feel natural and match the welcoming tone we&apos;ve worked hard to build.", "Liam Foster", "Founder, Verde Studio", "LF"], ["It&apos;s like adding a dedicated customer-care teammate without adding another task to our team.", "Amara Brooks", "Operations, Hearth & Co.", "AB"]].map(([q, n, r, initials]) => <figure className="rounded-2xl border border-white/10 bg-white/5 p-6" key={n}><Quote className="h-5 w-5 text-blue-300" /><blockquote className="mt-5 text-base leading-7 text-slate-200">“{q}”</blockquote><figcaption className="mt-7 flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-blue-500/20 text-xs font-semibold text-blue-200">{initials}</span><span><b className="block text-sm text-white">{n}</b><small className="text-slate-400">{r}</small></span></figcaption></figure>)}</div></div></section>

    <section id="pricing" className="py-24 sm:py-32"><div className="mx-auto max-w-6xl px-6 text-center"><p className="eyebrow">SIMPLE, TRANSPARENT PRICING</p><h2>Make every review count.</h2><p className="copy mx-auto">Start free. Upgrade only when your review volume grows.</p><div className="mt-14 grid gap-4 text-left lg:grid-cols-3">{[["Starter", "$29", "For one location getting started", ["1 Google Business Profile", "Automatic review detection", "Brand voice settings"]], ["Growth", "$79", "For growing teams that want full automation", ["Everything in Starter", "Automatic publishing", "Priority support", "Advanced automation controls"]], ["Agency", "Let&apos;s talk", "For teams planning multiple locations", ["Everything in Growth", "Multi-location roadmap access", "Dedicated onboarding"]]].map(([name, price, desc, list], i) => <article className={`relative rounded-2xl border p-7 ${i === 1 ? "border-[#2857f5] bg-[#f5f7ff] shadow-xl shadow-blue-900/10" : "border-slate-200 bg-white"}`} key={String(name)}><>{i === 1 && <span className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-[#2857f5] px-3 py-1 text-xs font-semibold text-white">MOST POPULAR</span>}</><h3>{name}</h3><p className="mt-2 min-h-10 text-sm text-slate-600">{desc}</p><p className="mt-6 text-4xl font-semibold tracking-[-.05em]">{price}<span className="text-base font-medium text-slate-400">{i < 2 && "/mo"}</span></p><Link href="/register" className={`mt-7 block rounded-full py-3 text-center text-sm font-semibold ${i === 1 ? "bg-[#2857f5] text-white" : "border border-slate-200"}`}>{i === 2 ? "Contact us" : "Start Free"}</Link><ul className="mt-7 space-y-3 border-t border-slate-200 pt-6 text-sm text-slate-600">{(list as string[]).map(x => <li key={x}><Check className="mr-2 inline h-4 w-4 text-[#2857f5]" />{x}</li>)}</ul></article>)}</div></div></section>

    <section id="faq" className="border-t border-slate-200 py-24"><div className="mx-auto grid max-w-6xl gap-12 px-6 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">QUESTIONS, ANSWERED</p><h2>Everything you need to know.</h2><p className="copy">Still curious? We&apos;re happy to help.</p><a className="text-link" href="mailto:hello@replypilot.com">Talk to us <ArrowRight /></a></div><div>{faqs.map(([q, a]) => <details className="group border-b border-slate-200 py-5" key={q}><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold">{q}<ChevronDown className="h-5 w-5 shrink-0 text-slate-400 transition group-open:rotate-180" /></summary><p className="max-w-xl pt-3 text-sm leading-6 text-slate-600">{a}</p></details>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-6 pb-20"><div className="relative overflow-hidden rounded-3xl bg-[#2857f5] px-6 py-16 text-center text-white sm:px-12 sm:py-24"><div className="cta-orb cta-orb-a" /><div className="cta-orb cta-orb-b" /><div className="relative"><p className="text-sm font-semibold text-blue-200">YOUR NEXT REVIEW IS WAITING</p><h2 className="mx-auto mt-4 max-w-3xl text-white">Never Leave Another Customer Review Unanswered.</h2><p className="mx-auto mt-5 max-w-xl text-blue-100">Connect once, then let Reply Pilot work around the clock—automatically publishing thoughtful replies in your voice.</p><Link href="/register" className="mt-8 inline-block rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-[#2857f5] shadow-lg transition hover:-translate-y-0.5">Start Free <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div></div></section>

    <footer className="border-t border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-12 sm:grid-cols-2 lg:grid-cols-5"><div className="lg:col-span-2"><Logo /><p className="mt-4 max-w-xs text-sm leading-6 text-slate-500">The always-on teammate for thoughtful Google review replies.</p></div>{[["Product", "Features", "Pricing", "Changelog"], ["Company", "Documentation", "Contact", "Privacy", "Terms"], ["Follow", "LinkedIn", "X / Twitter"]].map(([head, ...links]) => <div key={head}><p className="text-sm font-semibold">{head}</p>{links.map(x => <a className="mt-3 block text-sm text-slate-500 hover:text-[#2857f5]" href="#" key={x}>{x}</a>)}</div>)}</div><div className="mx-auto flex max-w-7xl flex-col gap-2 border-t border-slate-100 px-6 py-6 text-xs text-slate-400 sm:flex-row sm:justify-between"><span>© 2026 Reply Pilot. All rights reserved.</span><span className="inline-flex items-center gap-1"><LockKeyhole className="h-3 w-3" /> Secure Google Business Profile connection</span></div></footer>
  </main>;
}

function FlowCard({ n, title, text, icon, active = false }: { n: string; title: string; text: string; icon: string; active?: boolean }) { return <div className={`relative rounded-xl border p-4 ${active ? "border-blue-200 bg-blue-50" : "border-slate-200 bg-white"}`}><span className="text-[10px] font-bold text-slate-400">{n}</span><span className={`float-right grid h-7 w-7 place-items-center rounded-lg text-xs ${active ? "bg-[#2857f5] text-white" : "bg-slate-100 text-slate-500"}`}>{icon}</span><p className="mt-5 text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-slate-500">{text}</p></div>; }
function Stat({ value, label }: { value: string; label: string }) { return <div className="p-5"><p className="text-2xl font-semibold tracking-[-.05em] text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>; }
function DashStat({ n, t }: { n: string; t: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xl font-semibold tracking-[-.04em]">{n}</p><p className="mt-1 text-xs text-slate-500">{t}</p></div>; }
function Result({ n, l }: { n: string; l: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-4xl font-semibold tracking-[-.06em] text-[#2857f5]">{n}</p><p className="mt-2 text-sm text-slate-500">{l}</p></div>; }
